# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155700cbd424cd4499c43e5728c43cedf034772647d6a15796a1841fc6d6ffe016cc1b9c33e5a091229ecc2bbf6a564e7c4917c864f8eab1b5b3721bb7bd7df5

test:
  secret_key_base: d8a963dc2b0b1ab1163d245b9eb3526387cbfbb768804160ad7b5b71620464bcb5994210ae4b533cc31bb10dafc199928b82aed5017d7e1abb534bb08fb6a408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
